Repository alexrichardson1/NFT-Toolkit, pull requests merged in 2021-12, with the labels that each got.

#112 Gen Speed Improvements
  .github/workflows/client.yml
  .github/workflows/deploy.yml
  client/Dockerfile
  client/package.json
  client/src/react-app-env.d.ts
  client/src/utils/constants.ts
  client/src/utils/formUtils.ts
  client/yarn.lock
  docker-compose.yml
  ml/Dockerfile
  ml/requirements.txt
  nginx/configs/default.conf
  server/smart-contracts/contracts/nft.sol
  server/src/controllers/collection.ts
  server/src/controllers/generateArt.ts
  server/src/models/collection.ts
  server/src/routes/collection.ts
Labels: ci, fix

#111 Form Recommendations
  client/src/App.tsx
  client/src/actions/formActions.ts
  client/src/components/common/PageHeader.tsx
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/create-collection-form/FormButtons.tsx
  client/src/components/create-collection-form/form-steps/GeneralInfoStep.tsx
  client/src/components/create-collection-form/form-steps/LayerImageUpload.tsx
  client/src/components/create-collection-form/form-steps/LayerSelectionStep.tsx
  client/src/components/create-collection-form/form-steps/RecommendationsStep.tsx
  client/src/components/create-collection-form/form-steps/StaticArtStep.tsx
  client/src/components/create-collection-form/form-steps/TierSelectionStep.tsx
  client/src/components/create-collection-form/form-steps/TypeOfArtStep.tsx
  client/src/hooks/useArray.ts
  client/src/lib/global.d.ts
  client/src/pages/Error404.tsx
  client/src/pages/MintingPage.tsx
  client/src/reducers/formReducer.ts
  client/src/reducers/formReducerTypes.ts
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/common/OrderableList.test.tsx
  client/src/test/components/common/__snapshots__/OrderableList.test.tsx.snap
  client/src/test/components/create-collection-form/CreateCollectionForm.test.tsx
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/__snapshots__/FormButtons.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/GeneralInfoStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerImageUpload.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/StaticArtStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/TierSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GeneralInfoStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerSelectionStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/StaticArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/TierSelectionStep.test.tsx.snap
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/reducers/formReducer.test.ts
  client/src/utils/formUtils.ts
Labels: feature, fix, chore

#119 Rarity UI Help
  client/src/actions/formActions.ts
  client/src/components/common/OrderableListItem.tsx
  client/src/components/common/RarityProgressBar.tsx
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/create-collection-form/form-steps/LayerImageUpload.tsx
  client/src/components/create-collection-form/form-steps/LayerSelectionStep.tsx
  client/src/components/create-collection-form/form-steps/TierSelectionStep.tsx
  client/src/components/create-collection-form/tabs/Tabs.tsx
  client/src/lib/global.d.ts
  client/src/pages/MintingPage.tsx
  client/src/reducers/formReducer.ts
  client/src/reducers/formReducerTypes.ts
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/GeneralInfoStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerImageUpload.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/StaticArtStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/TierSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GeneralInfoStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerSelectionStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/StaticArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/TierSelectionStep.test.tsx.snap
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/reducers/formReducer.test.ts
  client/src/test/utils/formUtils.test.ts
  client/src/utils/formUtils.ts
Labels: feature

#124 Client Cleanup
  client/package.json
  client/src/actions/formActions.ts
  client/src/components/common/ChoiceCard.tsx
  client/src/components/common/InfoToolTip.tsx
  client/src/components/common/MobileMenu.tsx
  client/src/components/common/PageHeader.tsx
  client/src/components/common/SvgLogo.tsx
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/create-collection-form/FormAlert.tsx
  client/src/components/create-collection-form/form-steps/RecommendationsStep.tsx
  client/src/components/create-collection-form/form-steps/TypeOfArtStep.tsx
  client/src/components/create-collection-form/tabs/TabPanel.tsx
  client/src/context/network/NetworkProvider.tsx
  client/src/context/snackbar/SnackbarProvider.tsx
  client/src/context/theme/ThemeProvider.tsx
  client/src/hooks/useCounter.ts
  client/src/reducers/formReducer.ts
  client/src/store/StoreProvider.tsx
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/common/__snapshots__/MobileMenu.test.tsx.snap
  client/src/test/components/common/__snapshots__/Networks.test.tsx.snap
  client/src/test/components/common/__snapshots__/SvgLogo.test.tsx.snap
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GeneralInfoStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/StaticArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/TierSelectionStep.test.tsx.snap
  client/src/test/components/create-collection-form/tabs/__snapshots__/TabPanel.test.tsx.snap
  client/src/test/components/navbar/__snapshots__/Navbar.test.tsx.snap
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/pages/__snapshots__/MintingPages.test.tsx.snap
  client/src/utils/coinGecko.ts
  client/src/utils/collection-form/collectionHandles.ts
  client/src/utils/collection-form/formHandles.ts
  client/src/utils/collection-form/imageHandles.ts
  client/src/utils/collection-form/layerHandles.ts
  client/src/utils/collection-form/predictionHandles.ts
  client/src/utils/collection-form/tierHandles.ts
  client/yarn.lock
Labels: refactor
