Repository alexrichardson1/NFT-Toolkit, pull requests merged in 2021-11, with the labels that each got.

#47 Flask & Docker setup
  .github/workflows/python.yml
  ml/Dockerfile
  ml/api/__init__.py
  ml/api/price_predicition.py
  ml/data_collection.py
  ml/requirements.txt
  ml/test/__init__.py
  ml/test/test_api.py
  requirements.txt
Labels: feature, ci

#48 Art generation
  server/src/controllers/generateArt.ts
  server/src/tests/generateArt.test.ts
  server/src/tests/generateArtStress.test.ts
Labels: test

#52 Minting page
  .eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/actions/progressActions.ts
  client/src/components/common/GenericFallback.tsx
  client/src/components/common/SvgLogo.tsx
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/create-collection-form/formUtils.ts
  client/src/components/create-collection-form/tabs/TabPanel.tsx
  client/src/hooks/useAppDispatch.ts
  client/src/hooks/useAppSelector.ts
  client/src/index.tsx
  client/src/pages/MintingPage.tsx
  client/src/react-app-env.d.ts
  client/src/reducers/progressReducer.ts
  client/src/reducers/storeReducer.ts
  client/src/store/StoreProvider.tsx
  client/src/store/store.ts
  client/src/test/App.test.tsx
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/common/GenericFallback.test.tsx
  client/src/test/components/common/__snapshots__/GenericFallback.test.tsx.snap
  client/src/test/components/common/__snapshots__/MobileMenu.test.tsx.snap
  client/src/test/components/common/__snapshots__/Networks.test.tsx.snap
  client/src/test/components/common/__snapshots__/SvgLogo.test.tsx.snap
  client/src/test/components/create-collection-form/CreateCollectionForm.test.tsx
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/tabs/__snapshots__/TabPanel.test.tsx.snap
  client/src/test/components/navbar/__snapshots__/Navbar.test.tsx.snap
  client/src/test/components/wallet/Wallet.test.tsx
  client/src/test/components/wallet/__snapshots__/Wallet.test.tsx.snap
  client/src/test/components/wallet/walletUtils.test.ts
  client/src/test/index.test.tsx
  client/src/test/pages/MintingPages.test.tsx
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/pages/__snapshots__/MintingPages.test.tsx.snap
  client/src/test/reducers/progressReducer.test.ts
  client/src/test/utils/constants.test.ts
  client/src/utils/constants.ts
  client/yarn.lock
  server/src/controllers/collection.ts
  server/src/routes/collection.ts
  server/src/tests/controllers/collection.test.ts
Labels: feature, test

#68 Remove alpine node version
  client/Dockerfile
Labels: ci, fix

#71 Ci fixes
  .eslintrc.json
  client/Dockerfile
  client/package.json
  client/src/components/common/SvgLogo.tsx
  client/src/components/create-collection-form/tabs/Tabs.tsx
  client/src/components/wallet/Wallet.tsx
  client/src/pages/MintingPage.tsx
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/common/__snapshots__/MobileMenu.test.tsx.snap
  client/src/test/components/common/__snapshots__/Networks.test.tsx.snap
  client/src/test/components/common/__snapshots__/SvgLogo.test.tsx.snap
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/navbar/__snapshots__/Navbar.test.tsx.snap
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/pages/__snapshots__/MintingPages.test.tsx.snap
  client/src/typechain/hardhat.d.ts
  package.json
  server/hardhat.config.ts
  yarn.lock
Labels: ci, fix

#72 Fix useEffect in Minting Page
  client/src/pages/MintingPage.tsx
Labels: fix

#73 Generative art form
  client/package.json
  client/src/actions/formActions.ts
  client/src/components/common/ChoiceCard.tsx
  client/src/components/common/Input.tsx
  client/src/components/common/OrderableListItem.tsx
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/create-collection-form/FormAlert.tsx
  client/src/components/create-collection-form/FormButtons.tsx
  client/src/components/create-collection-form/ImageUploadWithTabs.tsx
  client/src/components/create-collection-form/OrderableList.tsx
  client/src/components/create-collection-form/custom-image-upload/ImageUpload.tsx
  client/src/components/create-collection-form/form-steps/GenArtStep.tsx
  client/src/components/create-collection-form/form-steps/GeneralInfoStep.tsx
  client/src/components/create-collection-form/form-steps/LayerImageUpload.tsx
  client/src/components/create-collection-form/form-steps/LayerSelectionStep.tsx
  client/src/components/create-collection-form/form-steps/StaticArtStep.tsx
  client/src/components/create-collection-form/form-steps/TypeOfArtStep.tsx
  client/src/components/create-collection-form/tabs/TabPanel.tsx
  client/src/components/create-collection-form/tabs/Tabs.tsx
  client/src/hooks/useArray.ts
  client/src/images/generativeIcon.svg
  client/src/images/staticIcon.svg
  client/src/lib/global.d.ts
  client/src/pages/MintingPage.tsx
  client/src/reducers/formReducer.ts
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/common/__snapshots__/Input.test.tsx.snap
  client/src/test/components/common/__snapshots__/MobileMenu.test.tsx.snap
  client/src/test/components/common/__snapshots__/Networks.test.tsx.snap
  client/src/test/components/create-collection-form/CreateCollectionForm.test.tsx
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/custom-image-upload/ImageUpload.test.tsx
  client/src/test/components/create-collection-form/custom-image-upload/__snapshots__/ImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/GenArtStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/GeneralInfoStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/StaticArtStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GenArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GeneralInfoStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/StaticArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/tabs/Tabs.test.tsx
  client/src/test/components/create-collection-form/tabs/__snapshots__/TabPanel.test.tsx.snap
  client/src/test/components/create-collection-form/tabs/__snapshots__/Tabs.test.tsx.snap
  client/src/test/components/navbar/Navbar.test.tsx
  client/src/test/components/navbar/__snapshots__/Navbar.test.tsx.snap
  client/src/test/components/wallet/Wallet.test.tsx
  client/src/test/components/wallet/__snapshots__/Wallet.test.tsx.snap
  client/src/test/context/snackbar/__snapshots__/SnackbarProvider.test.tsx.snap
  client/src/test/pages/MintingPages.test.tsx
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/pages/__snapshots__/MintingPages.test.tsx.snap
  client/src/test/reducers/formReducer.test.ts
  client/src/test/utils/coinGecko.test.ts
  client/src/test/utils/formUtils.test.ts
  client/src/test/utils/pages.test.ts
  client/src/utils/coinGecko.ts
  client/src/utils/constants.ts
  client/src/utils/formUtils.ts
  client/src/utils/pages.ts
  client/yarn.lock
  git-hooks/pre-push.py
Labels: feature, ci, build
