Repository alexrichardson1/NFT-Toolkit, pull requests merged in 2022-01, with the labels that each got.

#144 My Collections Page
  client/src/App.tsx
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/marketplace/DisplayCard.tsx
  client/src/components/marketplace/Market.tsx
  client/src/components/marketplace/PurchasePage.tsx
  client/src/components/marketplace/displaycard.css
  client/src/components/my-collections/MyCollectionCard.tsx
  client/src/components/my-collections/myCollCard.css
  client/src/images/tether.svg
  client/src/lib/global.d.ts
  client/src/pages/MintingPage.tsx
  client/src/pages/MyCollectionsPage.tsx
  client/src/reducers/formReducer.ts
  client/src/test/__snapshots__/App.test.tsx.snap
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/GeneralInfoStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerImageUpload.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/StaticArtStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/TierSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GeneralInfoStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerSelectionStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/StaticArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/TierSelectionStep.test.tsx.snap
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/pages/__snapshots__/MintingPages.test.tsx.snap
  client/src/test/reducers/formReducer.test.ts
  client/src/test/utils/formUtils.test.ts
  client/src/typechain/NFT.d.ts
  client/src/typechain/factories/Market__factory.ts
  client/src/typechain/factories/NFT__factory.ts
  client/src/utils/collection-form/formHandles.ts
  client/src/utils/constants.ts
  client/src/utils/formUtils.ts
  server/smart-contracts/contracts/market.sol
  server/smart-contracts/contracts/nft.sol
  server/src/controllers/deployed.ts
  server/src/models/user.ts
Labels: feature, test

#146 Similar collections carousel
  client/package.json
  client/src/components/create-collection-form/CreateCollectionForm.tsx
  client/src/components/create-collection-form/form-steps/RecommendationsStep.tsx
  client/src/lib/global.d.ts
  client/src/reducers/formReducer.ts
  client/src/test/components/create-collection-form/__snapshots__/CreateCollectionForm.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/GeneralInfoStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerImageUpload.test.tsx
  client/src/test/components/create-collection-form/form-steps/LayerSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/StaticArtStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/TierSelectionStep.test.tsx
  client/src/test/components/create-collection-form/form-steps/__snapshots__/GeneralInfoStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerSelectionStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/StaticArtStep.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/TierSelectionStep.test.tsx.snap
  client/src/test/pages/__snapshots__/CreateCollectionPage.test.tsx.snap
  client/src/test/reducers/formReducer.test.ts
  client/src/test/utils/formUtils.test.ts
  client/src/utils/collection-form/formHandles.ts
  client/yarn.lock
  ml/api/routes.py
  ml/name-generator/img1.jpg
  ml/name-generator/img2.jpg
  ml/name-generator/img3.jpg
  ml/name-generator/img4.jpeg
Labels: feature

#149 Add automatic updates to the model and database
  ml/.dockerignore
  ml/Dockerfile
  ml/api/populate_database.py
  ml/update_scripts/crontab
  ml/update_scripts/fetch_more_collections.py
  ml/update_scripts/remove_duplicates.py
  ml/update_scripts/update_database.py
  ml/update_scripts/update_model.py
Labels: feature, ci

#152 Minor UI improvements
  client/src/components/create-collection-form/form-steps/LayerImageUpload.tsx
  client/src/components/create-collection-form/form-steps/LayerSelectionStep.tsx
  client/src/components/create-collection-form/form-steps/TierSelectionStep.tsx
  client/src/test/components/common/OrderableList.test.tsx
  client/src/test/components/common/SvgLogo.test.tsx
  client/src/test/components/common/__snapshots__/OrderableList.test.tsx.snap
  client/src/test/components/common/__snapshots__/SvgLogo.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/LayerImageUpload.test.tsx
  client/src/test/components/create-collection-form/form-steps/__snapshots__/LayerImageUpload.test.tsx.snap
  client/src/test/components/create-collection-form/form-steps/__snapshots__/TierSelectionStep.test.tsx.snap
Labels: feature, fix

#155 Fix canvas installation in Docker
  server/Dockerfile
Labels: ci, fix

#157 ML - Use Birch model
  ml/api/collection_model
  ml/api/models/prediction_model_abstract.py
  ml/api/models/prediction_model_affinity_prop_name.py
  ml/api/models/prediction_model_affinity_prop_name_score.py
Labels: feature

#159 Spelling Error Recommendation Page
  client/src/components/create-collection-form/form-steps/RecommendationsStep.tsx
Labels: fix
